### ISSUE TITLE
Can't craft the MalisisDoor, spruce trapdoor.

### ISSUE THREAD

**Issue by RuffleSteels** [ReadOnly-Mods/Galacticraft-Pack#10]
## Bug Description
When i try to craft a spruce trapdoor from the mod in the pack called MalisisDoor, it makes a regular oak trapdoor from minecraft. I would suggest disabling the recipe for trapdoor in CraftTweaks

### Did this work in the previous version?
No

## Client Information
* Modpack Version: 3.2.0
* Launcher Used: CurseForge Desktop

* Java Version: 1.12.2
* Memory Allocated: 8GB
* Server/LAN/Single Player: SinglePlayer
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: Survival
* Additional Content Installed: None

**Comment by RuffleSteels** [comment]
when will this be fixed?

**Comment by ROMVoid95** [comment]
Your free to download the new zenscript file referenced in b848755 and add it tp your end, The next update isn't planned for another 2 weeks
