### ISSUE TITLE
I would suggest you add RefinedStorage, IronChests, DarkUtils

### ISSUE THREAD

**Issue by RuffleSteels** [ReadOnly-Mods/Galacticraft-Pack#11]
## Context
I would like to reccomend RefinedStorage, IronChests, and DarkUtils as they are very good mods and increase the amount to do.

## Mod Details
* Name: DarkUtils
* CurseForge Link: https://www.curseforge.com/minecraft/mc-mods/dark-utilities

* Name: RefinedStorage
* CurseForge Link: https://www.curseforge.com/minecraft/mc-mods/refined-storage

* Name: IronChests
* CurseForge Link: https://www.curseforge.com/minecraft/mc-mods/iron-chests

**Comment by ROMVoid95** [comment]
I'll consider DarkUtils for next update
