### ISSUE TITLE
Post Initialization freezes on BuildCraft when installing optifine

### ISSUE THREAD

**Issue by RuffleSteels** [ReadOnly-Mods/Galacticraft-Pack#12]
## Bug Description
When I install optifine the game freezes on the loading screen when Initializing Buildcraft

### Did this work in the previous version?
no

## Client Information
* Modpack Version: 3.2.0
* Launcher Used: CurseForge Desktop

* Java Version: 1.12.2
* Memory Allocated: 8GB
* Server/LAN/Single Player: singleplayer
* Optifine Installed: yes
* Shaders Enabled: no

## World Information
* Modpack Version world created in: 3.1.2
* Additional Content Installed: optifine

**Comment by ROMVoid95** [comment]
Cannot offer support for Optifine
