### ISSUE TITLE
[配方缺失]我不能合成开放式电脑模组里的键盘

### ISSUE THREAD

**Issue by ZYLHL** [ReadOnly-Mods/Galacticraft-Pack#15]
## Bug Description

配方缺失，合成不了开放式电脑这个模组的键盘配件，不能合成就不能在生存模式里与开放式电脑的终端进行交互。

### Did this work in the previous version?

我不清楚，我是直接玩的最新正式版本v3.x，可能旧版本也不行吧。

## Steps to Reproduce (for bugs)

1. 玩开放式电脑模组的时候
2. 做出了机箱和屏幕，唯独键盘没法制作与合成。

## Logs

* Client/Server Log:
* Crash Log:
这不是导致客户端崩溃的致命错误，故无需上传崩溃和记录日志。

## Client Information
* Modpack Version: 3.1.2
* Launcher Used: MultiMC Launcher

* Java Version: Java 8
* Memory Allocated: 8192MB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.1.2
* Additional Content Installed: Smooth Font(平滑字体模组)

**Comment by ROMVoid95** [comment]
change the following option to false in `randomtweaks.cfg`
```
    # Changes the names of the stone and wooden buttons so that they describe their type.
    # Default: false
    B:betterButtonNames=true
```
