### ISSUE TITLE
Tier 2 Rocket and Buggy Schematics missing?

### ISSUE THREAD

**Issue by imyy4u99** [ReadOnly-Mods/Galacticraft-Pack#17]
I have searched 7 different moon dungeons and have not found either of these schematics.  Is is possible to find these or can you only create them while in creative?

**Comment by ROMVoid95** [comment]
what schematics have you found

**Comment by imyy4u99** [comment]
5 times I found the GalaxySpace schematic box (includes the 5 durable schematics) and the other 2 times I got Environmental Protection Oxygen Tank.  It seems like it is only offering the GalaxySpace schematics in these dungeons.

**Comment by ROMVoid95** [comment]
I have an idea on how to fix this easily. Ill report back and close the issue once the change is made in a future push.

**Comment by imyy4u99** [comment]
I tried one more moon dungeon and got the oxygen tank schematic again.  I went ahead and created the buggy and tier 2 rocket schematics with creative so I can work towards Mars.

Hope you can get it figured out for a future push.

**Comment by ROMVoid95** [comment]
Triumph mod was added and rewards the player with a T2 schematic after they kill the boss and open the treasure chest
