### ISSUE TITLE
Java Issue

### ISSUE THREAD

**Issue by Dan-819** [ReadOnly-Mods/Galacticraft-Pack#19]
## Bug Description

![image](https://user-images.githubusercontent.com/97815302/149644146-b849eaf9-17ce-46de-9602-83ddfa92171b.png)
this is what happens when i try to start my server, i have everything set to 8gb of allocated ram.

### Did this work in the previous version?

Yes

## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version:3.3.0
* Launcher Used: Curseforge

* Java Version:8
* Memory Allocated: 8gb
* Server/LAN/Single Player: Server
* Optifine Installed: no
* Shaders Enabled: no

## World Information
* Modpack Version world created in:
* Additional Content Installed:

## Server Information
* Java Version:8
* Operating System:Windows
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by ROMVoid95** [comment]
seeing some characters in the screenshot that shouldn't be there, could you zip the following files and upload them please?
Files:
- settings.cfg
- logs/serverstarting.log
- start.bat

**Comment by Dan-819** [comment]
its not letting me send a zip file. just says "is not included in the list", can I email it or send it any other way?

**Comment by Dan-819** [comment]
managed to fix it, something to do with my java priorities or something. followed this video if curious: https://www.youtube.com/watch?v=01dqjZILu5s
