### ISSUE TITLE
Logistical transporter from mekanism replaced by itemduct from thermal dynamics

### ISSUE THREAD

**Issue by Gniemiec36** [ReadOnly-Mods/Galacticraft-Pack#21]
## Bug Description

 The logistical transporter pipes from mekanism are missing. They do not exist in jei or in creative. However, when I place the crafting recipe of a logistical transporter in a crafting table, it gives me an itemduct from thermal dynamics.

### Did this work in the previous version?

 yes

## Steps to Reproduce (for bugs)

 when i downloaded the modpack, after trying to automate steel ingots, I realised the logistical transporter was missing.
1.
2.
3.

## Logs
 no crash, just missing items

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version: 3.5.1
* Launcher Used: curseforge

* Java Version: 1.12.2
* Memory Allocated: 32GB
* Server/LAN/Single Player: single player
* Optifine Installed: no
* Shaders Enabled: no

## World Information
* Modpack Version world created in:
* Additional Content Installed: none

**Comment by ROMVoid95** [comment]
thats intended
