### ISSUE TITLE
RFTools Elevator is super slow

### ISSUE THREAD

**Issue by TarasK420** [ReadOnly-Mods/Galacticraft-Pack#3]
Just wanna make sure, is it intentional that the RFTools elevator has suddenly became much slower than normal after version 3.0?

**Comment by ROMVoid95** [comment]
it was reduced, can you show a video of how slow? it wasn't reduced more than .01 of its value

**Comment by TarasK420** [comment]
ok i will join the server and record. But there is really no reason to reduce its speed, why not just keep it standard? Unless...

**Comment by TarasK420** [comment]
https://drive.google.com/file/d/1x7wNDvdt1fPRV-VQvHJdpQBYtMbdFzLO/view?usp=sharing
thats the video

**Comment by ROMVoid95** [comment]
Okay, thats intended. the reason for the reduced speed is the fast jolt the elevator made was  calling block updated at an extreme rate on the server.

**Comment by TarasK420** [comment]
alrighty, i would better be using jetpack then
