### ISSUE TITLE
When using the Enderio Powered-Spawner it says 'Denied by other mod'

### ISSUE THREAD

**Issue by RuffleSteels** [ReadOnly-Mods/Galacticraft-Pack#4]
## Bug Description
When I use the Powered-Spawner, it doesnt spawn as it says denied by other mod. I have tried every mob in light and night but it doesnt work. I have not lit the area up as well.

### Did this work in the previous version?
No

## Logs
https://gist.github.com/Lollypoplove08/ad5c2b1b3db01f80bfd32a7d17ebab82

## Client Information
* Modpack Version: It doesnt work on all the versions
* Launcher Used: Curseforge Desktop

## World Information
* Modpack Version world created in: 1.12.2
* Additional Content Installed: none

**Comment by ROMVoid95** [comment]
It may be due to the InControl mod, i'll test this and fix accordingly. In the meantime try disabling the InControl mod.

**Comment by ROMVoid95** [comment]
@Lollypoplove08 You can fix this by simply deleting the `spawn.cfg` file inside `config/incontrol/` folder
