### ISSUE TITLE
the enderio restone conduit doesnt work.

### ISSUE THREAD

**Issue by RuffleSteels** [ReadOnly-Mods/Galacticraft-Pack#7]
## Bug Description
When I try to use the redstone conduit it doesnt send any sort of restone signal.

### Did this work in the previous version?
Unknown

## Logs
https://gist.github.com/Lollypoplove08/40f4467a399b326bd9c3f91c5c17008c

## Client Information
* Modpack Version: 3.1.3
* Launcher Used: CurseForge Desktop

## World Information
* Modpack Version world created in: 1.12.2
* Additional Content Installed: none

**Comment by ROMVoid95** [comment]
![image](https://user-images.githubusercontent.com/42848897/105521970-4363bf80-5ca2-11eb-9e2e-8612ecd8f948.png)

worked when tested, closing as there is no bug present that prevents the use of the conduit
