### ISSUE TITLE
After updating to latest release, my hunger doesnt go down.

### ISSUE THREAD

**Issue by RuffleSteels** [ReadOnly-Mods/Galacticraft-Pack#8]
## Bug Description
My hunger doent go down and im on normal mode.

### Did this work in the previous version?
Yes

## Logs
https://gist.github.com/Lollypoplove08/a9267c7ae3a3dee7f0c6464363ef52b7

## Client Information
* Modpack Version: 3.2.0
* Launcher Used: CurseForge Desktop

## World Information
* Modpack Version world created in: 1.12.2
* Additional Content Installed: none

**Comment by ROMVoid95** [comment]
@Lollypoplove08
 What difficulty are you on?

**Comment by RuffleSteels** [comment]
Normal (it says in dicription)
