### ISSUE TITLE
Duplicate mods making server crash.

### ISSUE THREAD

**Issue by RetroSpectra** [ReadOnly-Mods/Galacticraft-Pack#9]
## Bug Description

Went to load server modpack onto server, console logs 3 mods with duplicate issues, Extra Planets, More Planets, and Random Tweaks. When I deleted the extra .jar files, I also noticed Galactic Tweaks had a duplicate and deleted that.

### Did this work in the previous version?

Did not have previous version.

## Steps to Reproduce (for bugs)

1. Using ExtraVM Server Hosting, load modpack with assistance from their staff.
2. Was told duplicate mods were causing issues.
3. Went to C:\Users\username\Downloads\Galacticraft-Pack_3.2.0-Server\mods and located offending files.

## Logs

* Client/Server Log:
* Crash Log: 

## Client Information
* Modpack Version: Galacticraft-Pack_3.2.0-Server
* Launcher Used: not in game

* Java Version: 1.12.2
* Memory Allocated: 4GB
* Server/LAN/Single Player: Server
* Optifine Installed: N/A
* Shaders Enabled: N/A

## World Information
* Modpack Version world created in: n/a
* Additional Content Installed: n/a

## Server Information
* Java Version: unknown
* Operating System: unknown
* Hoster/Hosting Solution: ExtraVM
* Sponge (Non-Vanilla Forge) Server:

Fixed by deleting the files, probably not a huge bug fix.

**Comment by RetroSpectra** [comment]
actually I just reviewed your changelog, it just looks like you forgot to delete the old versions.

**Comment by ROMVoid95** [comment]
Will upload a fixed zip right away. Not sure how this got by but thanks for letting me know

**Comment by ROMVoid95** [comment]
https://www.curseforge.com/minecraft/modpacks/galacticraft-pack/files/3179343

fixed server-files uploaded
